linters-settings:
  goimports:
    # Separate internal packages from external
    local-prefixes: github.com/saltpay/transaction-card-validator

linters:
  # Enable extra linters besides the default ones
  enable:
    - goimports
    - godot
    - goconst
    - gofumpt
    - govet
    - stylecheck
    - unconvert
    - unparam
    - misspell
    - whitespace
    - bodyclose
