{{- if .Values.validator.pdb.enabled -}}
{{- range $validator := $.Values.validator.services }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "transaction-card-validator.name" $ }}-{{ $validator.name }}
  labels:
    {{- include "transaction-card-validator.labels" $ | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "transaction-card-validator.name" $ }}-{{ $validator.name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  {{- if $.Values.validator.pdb.minAvailable }}
  minAvailable: {{ $.Values.validator.pdb.minAvailable | int }}
  {{- end }}
  {{- if $.Values.validator.pdb.maxUnavailable }}
  maxUnavailable: {{ $.Values.validator.pdb.maxUnavailable | int }}
  {{- end }}
{{- end -}}
{{- end -}}
