{{- if .Values.validator.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.validator.serviceAccount.name }}
  labels:
    {{- include "transaction-card-validator.labels" $ | nindent 4 }}
  {{- with $.Values.validator.podAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
{{- end }}
