{{- range $validator := $.Values.validator.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "transaction-card-validator.name" $ }}-{{ $validator.name }}
  labels:
    app.kubernetes.io/name: {{ include "transaction-card-validator.name" $ }}-{{ $validator.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  type: {{ $.Values.validator.service.type }}
  ports:
    - port: {{ $.Values.validator.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "transaction-card-validator.name" $ }}-{{ $validator.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
{{- end }}
