// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package mocks

import (
	"github.com/saltpay/transaction-card-validator/internal/application/ports"
	"sync"
)

// Ensure, that ValidatorMock does implement ports.Validator.
// If this is not the case, regenerate this file with moq.
var _ ports.Validator = &ValidatorMock{}

// ValidatorMock is a mock implementation of ports.Validator.
//
// 	func TestSomethingThatUsesValidator(t *testing.T) {
//
// 		// make and configure a mocked ports.Validator
// 		mockedValidator := &ValidatorMock{
// 			ValidateFunc: func(msgDecoded interface{}) bool {
// 				panic("mock out the Validate method")
// 			},
// 		}
//
// 		// use mockedValidator in code that requires ports.Validator
// 		// and then make assertions.
//
// 	}
type ValidatorMock struct {
	// ValidateFunc mocks the Validate method.
	ValidateFunc func(msgDecoded interface{}) (bool, error)

	// calls tracks calls to the methods.
	calls struct {
		// Validate holds details about calls to the Validate method.
		Validate []struct {
			// MsgDecoded is the msgDecoded argument value.
			MsgDecoded interface{}
		}
	}
	lockValidate sync.RWMutex
}

// Validate calls ValidateFunc.
func (mock *ValidatorMock) Validate(msgDecoded interface{}) (bool, error) {
	if mock.ValidateFunc == nil {
		panic("ValidatorMock.ValidateFunc: method is nil but Validator.Validate was just called")
	}
	callInfo := struct {
		MsgDecoded interface{}
	}{
		MsgDecoded: msgDecoded,
	}
	mock.lockValidate.Lock()
	mock.calls.Validate = append(mock.calls.Validate, callInfo)
	mock.lockValidate.Unlock()
	return mock.ValidateFunc(msgDecoded)
}

// ValidateCalls gets all the calls that were made to Validate.
// Check the length with:
//     len(mockedValidator.ValidateCalls())
func (mock *ValidatorMock) ValidateCalls() []struct {
	MsgDecoded interface{}
} {
	var calls []struct {
		MsgDecoded interface{}
	}
	mock.lockValidate.RLock()
	calls = mock.calls.Validate
	mock.lockValidate.RUnlock()
	return calls
}
